INSERT INTO `Library` VALUES ('Banana Peel','Instant','50% Chance of -100 to target behind you',1,4);
INSERT INTO `Library` VALUES ('Bowling Ball','Instant','-100 to target (Old Green Shell)',1,1);
INSERT INTO `Library` VALUES ('Crowbar','Instant','-200 to person in front of you',1,4);
INSERT INTO `Library` VALUES ('Great Balls of Fire','Instant','Target gets -35.  Removes Lawn Bees effect. (Old Fire Flower)',1,1);
INSERT INTO `Library` VALUES ('Space Invaders','1 hour','User has one hour to get 3,600 points, or their points get reset to an hour ago',1,1);
INSERT INTO `Library` VALUES ('Stray Croquet Mallet','Instant','-100 to person in front of you (Old Red Shell)',1,4);
INSERT INTO `Library` VALUES ('Chi Blast','15 minutes','Target loses 25% points, and 3% chance -50 points (Old Hadouken)',2,1);
INSERT INTO `Library` VALUES ('Fisticuffs','Instant','Target gets -200 points (Old Hard Knuckle)',2,1);
INSERT INTO `Library` VALUES ('Plasma Grenade','Instant','You get -100 points, target gets -500 points (Old Charizard)',2,4);
INSERT INTO `Library` VALUES ('Unholy Water','12 hours?','Target -11 every time they hit /points (Old Holy Water)',2,1);
INSERT INTO `Library` VALUES ('Foam Dart','Instant','Top person''s points reduced by 15% (Old Blue Shell)',3,4);
INSERT INTO `Library` VALUES ('Get Over Here','Instant','10% chance of brining target to your position.',3,4);
INSERT INTO `Library` VALUES ('Golden Gun','Instant','Target''s points goes to 0.  1% chance of working.',3,1);
INSERT INTO `Library` VALUES ('Pandora''s Box','Instant','Target gets random penalty',3,1);
INSERT INTO `Library` VALUES ('Rail Gun','Instant','Target gets -1000 points.  10% chance of working.',3,1);
INSERT INTO `Library` VALUES ('Rocket Launcher','Instant','50% Chance target gets -100 points (Old SPNKR)',3,1);
INSERT INTO `Library` VALUES ('Samurai Sword','Instant','Target gets -500.  Only works on targets within 25% of your points. (Old Buster Sword)',3,1);
INSERT INTO `Library` VALUES ('Silencer','5 min','Target doesn''t gain points (Old Fus Ro Dah)',3,1);
INSERT INTO `Library` VALUES ('Slug Shooter','Instant','? -1000 points?',3,3);
INSERT INTO `Library` VALUES ('Cthulhu','Instant','Target gets badge, causes messages in weird encoding.',4,1);
INSERT INTO `Library` VALUES ('Dropbear','?','? ("nobody expects the spanish dropbear")',4,3);
INSERT INTO `Library` VALUES ('Frog','Instant','Target gets badge.  Causes all messages to be "Ribbit" (Old Poroggo)',4,1);
INSERT INTO `Library` VALUES ('Goomba','Instant','Sets points of target ahead of you to your point value - 1',4,4);
INSERT INTO `Library` VALUES ('Wreck-it Ralph','Instant','30% chance the user''s effects get cleared.',5,4);
INSERT INTO `Library` VALUES ('Mushroom','5 minutes','Gives self 2x points or /2 points.',1,4);
INSERT INTO `Library` VALUES ('Blind Date','Instant','Targets self.  Clears one permanent badge / effect.',2,4);
INSERT INTO `Library` VALUES ('Box of bees','Instant','Targets self with random penalty.',3,2);
INSERT INTO `Library` VALUES ('Leeroy Jenkins','15 minutes','Targets self.  Get leeroy jenkins messages.  Effects can not be used when active.',3,2);
INSERT INTO `Library` VALUES ('Leisure Suit','Instant','Targets self with Mom Voice penalty (points reset).',3,2);
INSERT INTO `Library` VALUES ('Portal Nun','30 minutes','Targets self. Get random messages about GLaDOS',3,2);
INSERT INTO `Library` VALUES ('NPC','30 minutes','Targets self.  Get random annoying messages from NPC.  80% points.',3,2);
INSERT INTO `Library` VALUES ('Chocobo','Instant','Chicken Badge.  No other effect.',3,4);
INSERT INTO `Library` VALUES ('Co-president''s Coin','Instant','Badge of "Core Value: Humility/Empowerment".  Changes title!',3,4);
INSERT INTO `Library` VALUES ('Fat Guys','Instant','Badge.  No other effect.',3,4);
INSERT INTO `Library` VALUES ('Pony','Instant','Badge.  No other effect.',3,4);
INSERT INTO `Library` VALUES ('Red Crystal','Instant','Badge.  No other effect.',3,4);
INSERT INTO `Library` VALUES ('Skinny Guys','Instant','Badge.  Gain 30% more points.',3,4);
INSERT INTO `Library` VALUES ('Space Towel','Instant','Plunger Badge.  No other effect. (Old Roger Wilco)',3,4);
INSERT INTO `Library` VALUES ('Game Controller','Instant','Badge.  Makes your text like old english.  Not sure effects.',4,4);
INSERT INTO `Library` VALUES ('King Graham','Instant','Badge.  No other effect.',4,4);
INSERT INTO `Library` VALUES ('Monarch''s Crown','Instant','Badge.  Not sure effects.',4,4);
INSERT INTO `Library` VALUES ('NES Controller','Instant','Badge.  Title.  Makes your text like old english.',4,4);
INSERT INTO `Library` VALUES ('Ocarina of Time','Instant','Badge.  Title.  Makes your text like old english.',4,4);
INSERT INTO `Library` VALUES ('Power Pellet: Blinky','Instant','Badge.  Collect all 4 to bypass daily point limits.',4,4);
INSERT INTO `Library` VALUES ('Power Pellet: Clyde','Instant','Badge.  Collect all 4 to bypass daily point limits.',4,4);
INSERT INTO `Library` VALUES ('Power Pellet: Inky','Instant','Badge.  Collect all 4 to bypass daily point limits.',4,4);
INSERT INTO `Library` VALUES ('Power Pellet: Pinky','Instant','Badge.  Collect all 4 to bypass daily point limits.',4,4);
INSERT INTO `Library` VALUES ('Triforce of Courage','Instant','Badge.  Title.  Makes your text like old english.  Collect all 3 to bypass daily item limits.',4,4);
INSERT INTO `Library` VALUES ('Triforce of Power','Instant','Badge.  Title.  Makes your text like old english.  Collect all 3 to bypass daily item limits.',4,4);
INSERT INTO `Library` VALUES ('Triforce of Wisdom','Instant','Badge.  Title.  Makes your text like old english.  Collect all 3 to bypass daily item limits.',4,4);
INSERT INTO `Library` VALUES ('Zelda Cartridge','Instant','Badge.  Title.  Makes your text like old english.',4,4);
INSERT INTO `Library` VALUES ('Game Cartridge','Instant','Badge. Game Cartridge. Makes your text like old english.',-1,4);
INSERT INTO `Library` VALUES ('Wooden Flute','?','?',-1,3);
INSERT INTO `Library` VALUES ('Bo Jackson','Instant','Adds 7 to target',1,0);
INSERT INTO `Library` VALUES ('Left-hand Man','Instant','Adds 50 to yourself (Old Biggs)',1,0);
INSERT INTO `Library` VALUES ('Pizza','Instant','Adds 50 to yourself',1,0);
INSERT INTO `Library` VALUES ('Right-Hand Man','Instant','Target gets 50 points (Old Wedge)',1,0);
INSERT INTO `Library` VALUES ('UUDDLRLRBA','Instant','Target gets 30 points',1,0);
INSERT INTO `Library` VALUES ('All-Terrain Vehicle','15 minutes','Point multipler of 2 to self (Old Warthog)',2,0);
INSERT INTO `Library` VALUES ('Buffalo','Instant','Adds 100 to target',2,0);
INSERT INTO `Library` VALUES ('Cardboard Box','Instant','You get person''s points ahead of you + 1',2,4);
INSERT INTO `Library` VALUES ('Da Da Da Da Daaa Da DAA da da','Instant','Gives 10 to self, and 1 item',2,0);
INSERT INTO `Library` VALUES ('Gold Ring','3 min','Protection to self from all items',2,0);
INSERT INTO `Library` VALUES ('Monster Trap','Instant','You get 35 points, and 1 item (Old Pokeball)',2,0);
INSERT INTO `Library` VALUES ('Trash Panda','3 attacks','Protection to self for next 3 items (Old Tanooki Suit)',2,0);
INSERT INTO `Library` VALUES ('7777','7 minutes','Point multiplier of 7 to self',3,0);
INSERT INTO `Library` VALUES ('Carbuncle','5 min','Reverses effects against items used against you',3,0);
INSERT INTO `Library` VALUES ('Flying Pig','30 minutes','30% chance points multiplied by 3 (Old Moogle)',3,0);
INSERT INTO `Library` VALUES ('Morph Ball','Instant','Moves self two spaces',3,0);
INSERT INTO `Library` VALUES ('Nitros Oxide','Instant','Moves self up 3 positions (Old Bullet Bill)',3,0);
INSERT INTO `Library` VALUES ('Princess','Instant','Removes Frog effect',3,4);
INSERT INTO `Library` VALUES ('Space Hamster','30 min','10% chance to self getting *10 points (Old Miniature Giant Space Hamster)',3,0);
INSERT INTO `Library` VALUES ('Space Suit','1 hour','Items do 50% damange to self (Old Varia Suit)',3,0);
INSERT INTO `Library` VALUES ('Star','5 minutes','Protection to self from all items',3,0);
INSERT INTO `Library` VALUES ('Strong Magnets','15 minutes','Protection to self from all items (Old Merger Beard)',3,0);
INSERT INTO `Library` VALUES ('Treasure Chest','Instant','Gives you 3 items',3,0);
INSERT INTO `Library` VALUES ('Ambrosia','Instant','Removes all effects, and cthulu and poroggo badges',4,4);
INSERT INTO `Library` VALUES ('Bentley the Dog','1 hour','10% chance of self getting *3.33 points (Old Rush The Dog)',4,0);
INSERT INTO `Library` VALUES ('Pink Plushy','Instant','Target gains 1,000 points (Old JigglyPuff)',4,0);
INSERT INTO `Library` VALUES ('Portals','Instant','You and the target swap points (Old Portal Gun)',4,4);
INSERT INTO `Library` VALUES ('Stab Rabbit','Instant','Reduces target''s point by 10% (?)',4,3);
INSERT INTO `Library` VALUES ('Pip-Boy','Instant','Get link, username, and password to source code',5,0);
INSERT INTO `Library` VALUES ('Boaty McBoatFace','Instant','Target gets 1,337,133,713,370 (Old Vanellope)',6,4);
INSERT INTO `Library` VALUES ('BadBreath','1 minute','Get 0 points, items have no effects','','');
INSERT INTO `Library` VALUES ('Bleeding','30 minutes','Items do 2 less points to you',NULL,'');
INSERT INTO `Library` VALUES ('CriticalHit','Instant','Get -5 points',NULL,NULL);
INSERT INTO `Library` VALUES ('Culture Shock','?','?',NULL,NULL);
INSERT INTO `Library` VALUES ('Dysentery','Instant','Get -20 points',NULL,NULL);
INSERT INTO `Library` VALUES ('Fear','10 times','Get 0 points',NULL,NULL);
INSERT INTO `Library` VALUES ('IceStorm','Instant','Lose 5% of points',NULL,NULL);
INSERT INTO `Library` VALUES ('Lycanthropy','Permanent','At midnight, items target self instead of specified target.  4% additional chance to get items.',NULL,NULL);
INSERT INTO `Library` VALUES ('MomVoice','1 hour','Points reset to 0.  No points gained for an hour.',NULL,NULL);
INSERT INTO `Library` VALUES ('Petrify','10 minutes','Get 0 points',NULL,NULL);
INSERT INTO `Library` VALUES ('Poison','Instant','Get -10 points',NULL,NULL);
INSERT INTO `Library` VALUES ('QuickSand','5 minutes','Get 0 points',NULL,NULL);
INSERT INTO `Library` VALUES ('Raptor','Instant','Lose 10% of points',NULL,NULL);
INSERT INTO `Library` VALUES ('Sandstorm','Instant','Lose 2% of points',NULL,NULL);
INSERT INTO `Library` VALUES ('ScopeCreep','1 hour','Get 50% of points',NULL,NULL);
INSERT INTO `Library` VALUES ('ShellShock','3 minutes','Items have no effect on player',NULL,NULL);
INSERT INTO `Library` VALUES ('Slow','15 minutes','Get 50% of points',NULL,NULL);
INSERT INTO `Library` VALUES ('TKO','1 minute','Get 0 points',NULL,NULL);
INSERT INTO `Library` VALUES ('Vampirism','Permanent','From 6 AM to 9 PM CST, you obtain vampire badge (eliminates item usage limits), and get -5 points on item usage.  Otherwise, nothing happens.',NULL,NULL);
INSERT INTO `Library` VALUES ('Zombie','1 hour','Items have no effect.  When zombie uses item on another player, they get zombie',NULL,NULL);
